CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902134525_InitialLeadSchema') THEN
    CREATE SEQUENCE lead_number_seq START WITH 1 INCREMENT BY 1 NO CYCLE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902134525_InitialLeadSchema') THEN
    CREATE TABLE "Leads" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LeadNumber" character varying(24) NOT NULL,
        "ServiceSlug" character varying(60) NOT NULL,
        "ServiceName" character varying(80) NOT NULL,
        "MovingFrom" character varying(80),
        "MovingTo" character varying(80),
        "StorageLocation" character varying(80),
        "MovingDate" date,
        "PropertyType" character varying(40),
        "MoveSize" character varying(120),
        "OfficeSize" character varying(60),
        "DeskCount" character varying(30),
        "VehicleType" character varying(40),
        "VehicleModel" character varying(80),
        "VehicleCondition" character varying(20),
        "GoodsType" character varying(80),
        "LoadDetails" character varying(120),
        "VehicleRequirement" character varying(60),
        "StorageType" character varying(40),
        "StorageSize" character varying(60),
        "StorageDuration" character varying(40),
        "CustomerName" character varying(80) NOT NULL,
        "Phone" character varying(20) NOT NULL,
        "Email" character varying(120),
        "PreferredContactMethod" character varying(20),
        "AdditionalRequirements" character varying(600),
        "Status" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Leads" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902134525_InitialLeadSchema') THEN
    CREATE INDEX "IX_Leads_CreatedAt" ON "Leads" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902134525_InitialLeadSchema') THEN
    CREATE UNIQUE INDEX "IX_Leads_LeadNumber" ON "Leads" ("LeadNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902134525_InitialLeadSchema') THEN
    CREATE INDEX "IX_Leads_Phone_CreatedAt" ON "Leads" ("Phone", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902134525_InitialLeadSchema') THEN
    CREATE INDEX "IX_Leads_Status" ON "Leads" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902134525_InitialLeadSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260902134525_InitialLeadSchema', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE INDEX "IX_Leads_CustomerName" ON "Leads" ("CustomerName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260910130928_AddIdentitySchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260910130928_AddIdentitySchema', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911091051_AddVendorSchema') THEN
    CREATE SEQUENCE vendor_number_seq START WITH 1 INCREMENT BY 1 NO CYCLE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911091051_AddVendorSchema') THEN
    CREATE TABLE "Vendors" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "VendorNumber" character varying(28) NOT NULL,
        "IdentityUserId" character varying(450) NOT NULL,
        "BusinessName" character varying(120) NOT NULL,
        "ContactPerson" character varying(80) NOT NULL,
        "Phone" character varying(20) NOT NULL,
        "Email" character varying(120) NOT NULL,
        "City" character varying(80) NOT NULL,
        "Address" character varying(250) NOT NULL,
        "GstNumber" character varying(20),
        "YearsOfExperience" integer NOT NULL,
        "OperatingLocations" character varying(250),
        "AdditionalInformation" character varying(600),
        "Status" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Vendors" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911091051_AddVendorSchema') THEN
    CREATE TABLE "VendorServices" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "VendorId" integer NOT NULL,
        "ServiceSlug" character varying(60) NOT NULL,
        "ServiceName" character varying(80) NOT NULL,
        CONSTRAINT "PK_VendorServices" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VendorServices_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911091051_AddVendorSchema') THEN
    CREATE INDEX "IX_Vendors_City" ON "Vendors" ("City");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911091051_AddVendorSchema') THEN
    CREATE INDEX "IX_Vendors_CreatedAt" ON "Vendors" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911091051_AddVendorSchema') THEN
    CREATE INDEX "IX_Vendors_Email" ON "Vendors" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911091051_AddVendorSchema') THEN
    CREATE UNIQUE INDEX "IX_Vendors_IdentityUserId" ON "Vendors" ("IdentityUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911091051_AddVendorSchema') THEN
    CREATE INDEX "IX_Vendors_Phone" ON "Vendors" ("Phone");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911091051_AddVendorSchema') THEN
    CREATE INDEX "IX_Vendors_Status" ON "Vendors" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911091051_AddVendorSchema') THEN
    CREATE UNIQUE INDEX "IX_Vendors_VendorNumber" ON "Vendors" ("VendorNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911091051_AddVendorSchema') THEN
    CREATE INDEX "IX_VendorServices_ServiceSlug" ON "VendorServices" ("ServiceSlug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911091051_AddVendorSchema') THEN
    CREATE UNIQUE INDEX "IX_VendorServices_VendorId_ServiceSlug" ON "VendorServices" ("VendorId", "ServiceSlug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911091051_AddVendorSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260911091051_AddVendorSchema', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911130405_AddLeadAssignments') THEN
    CREATE TABLE "LeadAssignments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LeadId" integer NOT NULL,
        "VendorId" integer NOT NULL,
        "Status" character varying(20) NOT NULL,
        "AssignedAt" timestamp with time zone NOT NULL,
        "ViewedAt" timestamp with time zone,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_LeadAssignments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LeadAssignments_Leads_LeadId" FOREIGN KEY ("LeadId") REFERENCES "Leads" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LeadAssignments_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911130405_AddLeadAssignments') THEN
    CREATE INDEX "IX_LeadAssignments_AssignedAt" ON "LeadAssignments" ("AssignedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911130405_AddLeadAssignments') THEN
    CREATE INDEX "IX_LeadAssignments_LeadId" ON "LeadAssignments" ("LeadId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911130405_AddLeadAssignments') THEN
    CREATE UNIQUE INDEX "IX_LeadAssignments_LeadId_VendorId" ON "LeadAssignments" ("LeadId", "VendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911130405_AddLeadAssignments') THEN
    CREATE INDEX "IX_LeadAssignments_VendorId_Status" ON "LeadAssignments" ("VendorId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911130405_AddLeadAssignments') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260911130405_AddLeadAssignments', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141335_AddQuotes') THEN
    CREATE SEQUENCE quote_number_seq START WITH 1 INCREMENT BY 1 NO CYCLE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141335_AddQuotes') THEN
    CREATE TABLE "Quotes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuoteNumber" character varying(28) NOT NULL,
        "LeadId" integer NOT NULL,
        "VendorId" integer NOT NULL,
        "BasePrice" numeric(18,2) NOT NULL,
        "PackingCharges" numeric(18,2) NOT NULL,
        "TransportationCharges" numeric(18,2) NOT NULL,
        "LoadingUnloadingCharges" numeric(18,2) NOT NULL,
        "AdditionalCharges" numeric(18,2) NOT NULL,
        "TotalAmount" numeric(18,2) NOT NULL,
        "EstimatedPickupDate" date,
        "EstimatedDeliveryDate" date,
        "EstimatedDeliveryDays" integer,
        "VendorNotes" character varying(800),
        "Status" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Quotes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Quotes_Leads_LeadId" FOREIGN KEY ("LeadId") REFERENCES "Leads" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Quotes_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141335_AddQuotes') THEN
    CREATE INDEX "IX_Quotes_CreatedAt" ON "Quotes" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141335_AddQuotes') THEN
    CREATE INDEX "IX_Quotes_LeadId" ON "Quotes" ("LeadId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141335_AddQuotes') THEN
    CREATE UNIQUE INDEX "IX_Quotes_LeadId_VendorId" ON "Quotes" ("LeadId", "VendorId") WHERE "Status" IN ('Draft', 'Submitted', 'UnderReview', 'Accepted');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141335_AddQuotes') THEN
    CREATE UNIQUE INDEX "IX_Quotes_QuoteNumber" ON "Quotes" ("QuoteNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141335_AddQuotes') THEN
    CREATE INDEX "IX_Quotes_Status" ON "Quotes" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141335_AddQuotes') THEN
    CREATE INDEX "IX_Quotes_VendorId" ON "Quotes" ("VendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141335_AddQuotes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260911141335_AddQuotes', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912080545_AddCustomerPortal') THEN
    ALTER TABLE "Leads" ADD "ConvertedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912080545_AddCustomerPortal') THEN
    ALTER TABLE "Leads" ADD "SelectedQuoteId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912080545_AddCustomerPortal') THEN
    ALTER TABLE "Leads" ADD "SelectedVendorId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912080545_AddCustomerPortal') THEN
    CREATE TABLE "CustomerAccessTokens" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LeadId" integer NOT NULL,
        "TokenHash" character varying(64) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "LastUsedAt" timestamp with time zone,
        "RevokedAt" timestamp with time zone,
        CONSTRAINT "PK_CustomerAccessTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CustomerAccessTokens_Leads_LeadId" FOREIGN KEY ("LeadId") REFERENCES "Leads" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912080545_AddCustomerPortal') THEN
    CREATE INDEX "IX_Leads_ConvertedAt" ON "Leads" ("ConvertedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912080545_AddCustomerPortal') THEN
    CREATE INDEX "IX_Leads_SelectedQuoteId" ON "Leads" ("SelectedQuoteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912080545_AddCustomerPortal') THEN
    CREATE INDEX "IX_Leads_SelectedVendorId" ON "Leads" ("SelectedVendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912080545_AddCustomerPortal') THEN
    CREATE INDEX "IX_CustomerAccessTokens_ExpiresAt" ON "CustomerAccessTokens" ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912080545_AddCustomerPortal') THEN
    CREATE INDEX "IX_CustomerAccessTokens_LeadId" ON "CustomerAccessTokens" ("LeadId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912080545_AddCustomerPortal') THEN
    CREATE UNIQUE INDEX "IX_CustomerAccessTokens_TokenHash" ON "CustomerAccessTokens" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912080545_AddCustomerPortal') THEN
    ALTER TABLE "Leads" ADD CONSTRAINT "FK_Leads_Quotes_SelectedQuoteId" FOREIGN KEY ("SelectedQuoteId") REFERENCES "Quotes" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912080545_AddCustomerPortal') THEN
    ALTER TABLE "Leads" ADD CONSTRAINT "FK_Leads_Vendors_SelectedVendorId" FOREIGN KEY ("SelectedVendorId") REFERENCES "Vendors" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912080545_AddCustomerPortal') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260912080545_AddCustomerPortal', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912094011_AddNotificationLogs') THEN
    CREATE TABLE "NotificationLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Type" character varying(40) NOT NULL,
        "Recipient" character varying(180) NOT NULL,
        "Subject" character varying(200) NOT NULL,
        "HtmlBody" text NOT NULL,
        "TextBody" text,
        "EntityType" character varying(40) NOT NULL,
        "EntityId" integer NOT NULL,
        "Status" character varying(20) NOT NULL,
        "AttemptCount" integer NOT NULL,
        "LastAttemptAt" timestamp with time zone,
        "SentAt" timestamp with time zone,
        "ErrorMessage" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_NotificationLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912094011_AddNotificationLogs') THEN
    CREATE INDEX "IX_NotificationLogs_CreatedAt" ON "NotificationLogs" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912094011_AddNotificationLogs') THEN
    CREATE INDEX "IX_NotificationLogs_Status" ON "NotificationLogs" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912094011_AddNotificationLogs') THEN
    CREATE INDEX "IX_NotificationLogs_Type" ON "NotificationLogs" ("Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912094011_AddNotificationLogs') THEN
    CREATE UNIQUE INDEX "IX_NotificationLogs_Type_EntityType_EntityId_Recipient" ON "NotificationLogs" ("Type", "EntityType", "EntityId", "Recipient");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912094011_AddNotificationLogs') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260912094011_AddNotificationLogs', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912143112_AddReviews') THEN
    CREATE TABLE "Reviews" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LeadId" integer NOT NULL,
        "VendorId" integer NOT NULL,
        "Rating" integer NOT NULL,
        "Title" character varying(120),
        "Comment" character varying(1000) NOT NULL,
        "CustomerNameSnapshot" character varying(80) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "ModerationNote" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "PublishedAt" timestamp with time zone,
        CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Reviews_Leads_LeadId" FOREIGN KEY ("LeadId") REFERENCES "Leads" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Reviews_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912143112_AddReviews') THEN
    CREATE INDEX "IX_Reviews_CreatedAt" ON "Reviews" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912143112_AddReviews') THEN
    CREATE UNIQUE INDEX "IX_Reviews_LeadId" ON "Reviews" ("LeadId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912143112_AddReviews') THEN
    CREATE INDEX "IX_Reviews_Rating" ON "Reviews" ("Rating");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912143112_AddReviews') THEN
    CREATE INDEX "IX_Reviews_Status" ON "Reviews" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912143112_AddReviews') THEN
    CREATE INDEX "IX_Reviews_VendorId" ON "Reviews" ("VendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912143112_AddReviews') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260912143112_AddReviews', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260913061817_AddSeoContent') THEN
    CREATE TABLE "Locations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(80) NOT NULL,
        "Slug" character varying(80) NOT NULL,
        "City" character varying(80) NOT NULL,
        "State" character varying(80) NOT NULL,
        "Country" character varying(60) NOT NULL,
        "ShortDescription" character varying(300) NOT NULL,
        "Content" text NOT NULL,
        "H1" character varying(160) NOT NULL,
        "MetaTitle" character varying(160) NOT NULL,
        "MetaDescription" character varying(320) NOT NULL,
        "OgTitle" character varying(160),
        "OgDescription" character varying(320),
        "OgImage" character varying(400),
        "IsPublished" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Locations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260913061817_AddSeoContent') THEN
    CREATE TABLE "Routes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FromLocationId" integer NOT NULL,
        "ToLocationId" integer NOT NULL,
        "Slug" character varying(160) NOT NULL,
        "H1" character varying(160) NOT NULL,
        "ShortDescription" character varying(300) NOT NULL,
        "Content" text NOT NULL,
        "MetaTitle" character varying(160) NOT NULL,
        "MetaDescription" character varying(320) NOT NULL,
        "OgTitle" character varying(160),
        "OgDescription" character varying(320),
        "OgImage" character varying(400),
        "IsPublished" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Routes" PRIMARY KEY ("Id"),
        CONSTRAINT ck_routes_distinct_endpoints CHECK ("FromLocationId" <> "ToLocationId"),
        CONSTRAINT "FK_Routes_Locations_FromLocationId" FOREIGN KEY ("FromLocationId") REFERENCES "Locations" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Routes_Locations_ToLocationId" FOREIGN KEY ("ToLocationId") REFERENCES "Locations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260913061817_AddSeoContent') THEN
    CREATE TABLE "Faqs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Question" character varying(300) NOT NULL,
        "Answer" character varying(2000) NOT NULL,
        "LocationId" integer,
        "RouteId" integer,
        "ServiceSlug" character varying(60),
        "DisplayOrder" integer NOT NULL,
        "IsPublished" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Faqs" PRIMARY KEY ("Id"),
        CONSTRAINT ck_faqs_single_owner CHECK ((CASE WHEN "LocationId" IS NULL THEN 0 ELSE 1 END) + (CASE WHEN "RouteId" IS NULL THEN 0 ELSE 1 END) + (CASE WHEN "ServiceSlug" IS NULL THEN 0 ELSE 1 END) = 1),
        CONSTRAINT "FK_Faqs_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES "Locations" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Faqs_Routes_RouteId" FOREIGN KEY ("RouteId") REFERENCES "Routes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260913061817_AddSeoContent') THEN
    CREATE INDEX "IX_Faqs_LocationId_DisplayOrder" ON "Faqs" ("LocationId", "DisplayOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260913061817_AddSeoContent') THEN
    CREATE INDEX "IX_Faqs_RouteId_DisplayOrder" ON "Faqs" ("RouteId", "DisplayOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260913061817_AddSeoContent') THEN
    CREATE INDEX "IX_Faqs_ServiceSlug_DisplayOrder" ON "Faqs" ("ServiceSlug", "DisplayOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260913061817_AddSeoContent') THEN
    CREATE INDEX "IX_Locations_IsPublished" ON "Locations" ("IsPublished");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260913061817_AddSeoContent') THEN
    CREATE UNIQUE INDEX "IX_Locations_Slug" ON "Locations" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260913061817_AddSeoContent') THEN
    CREATE UNIQUE INDEX "IX_Routes_FromLocationId_ToLocationId" ON "Routes" ("FromLocationId", "ToLocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260913061817_AddSeoContent') THEN
    CREATE INDEX "IX_Routes_IsPublished" ON "Routes" ("IsPublished");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260913061817_AddSeoContent') THEN
    CREATE UNIQUE INDEX "IX_Routes_Slug" ON "Routes" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260913061817_AddSeoContent') THEN
    CREATE INDEX "IX_Routes_ToLocationId" ON "Routes" ("ToLocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260913061817_AddSeoContent') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260913061817_AddSeoContent', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260915131341_AddAuditLog') THEN
    CREATE TABLE "AdminAuditLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AdminUserId" character varying(450) NOT NULL,
        "AdminEmail" character varying(180) NOT NULL,
        "Action" character varying(30) NOT NULL,
        "EntityType" character varying(40) NOT NULL,
        "EntityId" integer NOT NULL,
        "Description" character varying(400) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AdminAuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260915131341_AddAuditLog') THEN
    CREATE INDEX "IX_AdminAuditLogs_AdminUserId" ON "AdminAuditLogs" ("AdminUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260915131341_AddAuditLog') THEN
    CREATE INDEX "IX_AdminAuditLogs_CreatedAt" ON "AdminAuditLogs" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260915131341_AddAuditLog') THEN
    CREATE INDEX "IX_AdminAuditLogs_EntityType_EntityId" ON "AdminAuditLogs" ("EntityType", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260915131341_AddAuditLog') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260915131341_AddAuditLog', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923065948_PartnerEmailVerification') THEN
    CREATE TABLE "DataProtectionKeys" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FriendlyName" text,
        "Xml" text,
        CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923065948_PartnerEmailVerification') THEN
    CREATE TABLE "EmailVerifications" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Email" character varying(120) NOT NULL,
        "CodeHash" character varying(64) NOT NULL,
        "Attempts" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "VerifiedAt" timestamp with time zone,
        "TokenHash" character varying(64),
        "UsedAt" timestamp with time zone,
        CONSTRAINT "PK_EmailVerifications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923065948_PartnerEmailVerification') THEN
    CREATE INDEX "IX_EmailVerifications_CreatedAt" ON "EmailVerifications" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923065948_PartnerEmailVerification') THEN
    CREATE INDEX "IX_EmailVerifications_Email_CreatedAt" ON "EmailVerifications" ("Email", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923065948_PartnerEmailVerification') THEN
    CREATE UNIQUE INDEX "IX_EmailVerifications_TokenHash" ON "EmailVerifications" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923065948_PartnerEmailVerification') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260923065948_PartnerEmailVerification', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923071757_PartnerDocuments') THEN
    ALTER TABLE "Vendors" ADD "EmailVerifiedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923071757_PartnerDocuments') THEN
    ALTER TABLE "Vendors" ADD "PhoneVerifiedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923071757_PartnerDocuments') THEN
    CREATE TABLE "VendorDocuments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "VendorId" integer NOT NULL,
        "Type" character varying(30) NOT NULL,
        "StoragePath" character varying(300) NOT NULL,
        "ContentType" character varying(60) NOT NULL,
        "OriginalFileName" character varying(200) NOT NULL,
        "SizeBytes" bigint NOT NULL,
        "UploadedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_VendorDocuments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VendorDocuments_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923071757_PartnerDocuments') THEN
    CREATE UNIQUE INDEX "IX_VendorDocuments_VendorId_Type" ON "VendorDocuments" ("VendorId", "Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923071757_PartnerDocuments') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260923071757_PartnerDocuments', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923154028_LocationHeroImage') THEN
    ALTER TABLE "Locations" ADD "HeroImagePath" character varying(300);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923154028_LocationHeroImage') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260923154028_LocationHeroImage', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260926070202_RegistrationFee') THEN
    CREATE TABLE "RegistrationPayments" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Email" character varying(120) NOT NULL,
        "RazorpayOrderId" character varying(40) NOT NULL,
        "RazorpayPaymentId" character varying(40),
        "Amount" numeric(18,2) NOT NULL,
        "Currency" character varying(3) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "PaidAt" timestamp with time zone,
        "UsedAt" timestamp with time zone,
        "VendorId" integer,
        CONSTRAINT "PK_RegistrationPayments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RegistrationPayments_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260926070202_RegistrationFee') THEN
    CREATE INDEX "IX_RegistrationPayments_Email_CreatedAt" ON "RegistrationPayments" ("Email", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260926070202_RegistrationFee') THEN
    CREATE UNIQUE INDEX "IX_RegistrationPayments_RazorpayOrderId" ON "RegistrationPayments" ("RazorpayOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260926070202_RegistrationFee') THEN
    CREATE INDEX "IX_RegistrationPayments_Status" ON "RegistrationPayments" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260926070202_RegistrationFee') THEN
    CREATE INDEX "IX_RegistrationPayments_VendorId" ON "RegistrationPayments" ("VendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260926070202_RegistrationFee') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260926070202_RegistrationFee', '10.0.11');
    END IF;
END $EF$;
COMMIT;

